config/routes.rb
FamilyDoctor::Application.routes.draw do
  resources :experiences

  get "family_doctor/register"

  get "family_doctor/loginByOthers"

  post "/family_doctor/login"

  get "/family_doctor/login"

  get "/family_doctor/exit"

  get "family_doctor/index"

  resources :experiences
  resources :comments

  root :to => 'family_doctor#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :authorId, :content, :createTime, :experienceId

  @authorName

  def setAuthorName(name)
    @authorName = name
  end

  def getAuthorName
    return @authorName
  end

  def Comment.setAuthorNameBatch(comments)
     comments.each do|comment|
       comment.setAuthorName(User.find(comment.authorId).username)
     end
  end
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  attr_accessible :title, :authorId, :createTime, :endTime, :privilege, :startTime, :text, :category

  private
  @authorName
  @commentCount
  @categoryName
  @comments

  public
  def setAuthorName(name)
    @authorName = name
  end

  def getAuthorName
    return @authorName
  end

  def setCommentCount(count)
    @commentCount = count
  end

  def getCommentCount
    return @commentCount
  end


  def setCategoryName(name)
    @categoryName =name
  end

  def getCategoryName
    return @categoryName
  end

  def setComments(comments)
    @comments = comments
  end

  def getComments
    return @comments
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :qq, :address, :birthDay, :gender, :password, :phone, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController  < ApplicationController
  # To change this template use File | Settings | File Templates.
  def create
    if(session[:userid] == nil) then
      redirect_to :controller => 'family_doctor', :action => 'login', :notice => 'Your must login before add comment'
      return
    end
    @comment = Comment.new(params[:comment])
    @comment.authorId=session[:userid]
    @comment.createTime=Time.now
    @experience = Experience.find(@comment.experienceId)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @experience, notice: 'Comment was successfully added.' }
        format.json { render json: @experience, status: :created, location: @experience }
      else
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  # GET /experiences
  # GET /experiences.json
  def index
    category = params[:category]
    if(category != nil) then
      @experiences = Experience.find_all_by_privilege_and_category(1,category);
    else
      @experiences = Experience.find_all_by_privilege(1)
    end

    userid = params[:userid]
    if(userid != nil)
      @experiences = Experience.find_all_by_authorId(userid)
    end

    @experiences.each do |experience|
      commentsForExp = Comment.find_by_sql("select * from comments where experienceId='#{experience.id}' order by createTime desc limit 3")
      Comment.setAuthorNameBatch(commentsForExp)
      experience.setComments commentsForExp
      experience.setAuthorName(User.find(experience.authorId).username)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiences }
    end
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @experience = Experience.find(params[:id])
    @experience.setAuthorName(User.find(@experience.authorId).username)
    case @experience.category
      when 1
        @experience.setCategoryName 'beautify'
      when 2
        @experience.setCategoryName 'whitening'
      when 3
        @experience.setCategoryName 'hypertension'
      when 4
        @experience.setCategoryName 'diabetes'
      else
        @experience.setCategoryName nil
    end

    @experience.setComments(Comment.find_all_by_experienceId(@experience.id))
    Comment.setAuthorNameBatch(@experience.getComments)

    @comment = Comment.new
    @comment.experienceId = @experience.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@experience, @comment]}
    end
  end

  # GET /experiences/new
  # GET /experiences/new.json
  def new
    @experience = Experience.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experience }
    end
  end

  # GET /experiences/1/edit
  def edit
    @experience = Experience.find(params[:id])
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(params[:experience])
    @experience.authorId = session[:userid]
    @experience.createTime = Time.now

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render json: @experience, status: :created, location: @experience }
      else
        format.html { render action: "new" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiences/1
  # PUT /experiences/1.json
  def update
    @experience = Experience.find(params[:id])
    respond_to do |format|
      if @experience.update_attributes(params[:experience])
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/family_doctor_controller.rb
class FamilyDoctorController < ApplicationController
  def index
    redirect_to :action=>"index",:controller=>"experiences"
  end

  def login
    uname=params[:uName]
    upass=params[:uPass]
    session[:user]=nil
    user=User.find_all_by_username_and_password(uname,upass)
    if user && user.length == 1
      session[:user]=user[0]
      session[:username] =user[0].username
      session[:userid]=user[0].id
      @user=session[:user]
      redirect_to :action=>'index',:controller=>'family_doctor'
    else
      session[:user]=nil
      flash[:notice]='login failed!'
    end
  end

  def loginByOthers
    case params[:source]
      when "renren"
        FamilyDoctorController.loginByRenren
      when "qq"
        FamilyDoctorController.loginByQQ
      when "sina"
        FamilyDoctorController.loginBySina
      when "alipay"
        FamilyDoctorController.loginByAlipay
      else
        render :action => "login", :layout => false
    end
  end

  def exit
    session[:user]=nil
    redirect_to :action=>"index",:controller=>"family_doctor"
  end

  def register
    @user = User.new
    @user.username = "test"
    @user.password="123456"
    @user.phone=15210598765
    @user.qq=837965789
    @user.address="beijing"
    @user.gender="male"
    @user.birthDay=Time.mktime(1997,9)
    @user.save
  end

  private
  def FamilyDoctorController.loginByRenren
  end

  def FamilyDoctorController.loginByQQ
  end

  def FamilyDoctorController.loginBySina
  end

  def FamilyDoctorController.loginByAlipay
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/family_doctor_helper.rb
module FamilyDoctorHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <table class="contenttable" border="2">
    <tr>
      <td colspan="2">
        <% if @experience.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

              <ul>
                <% @experience.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </td>
    </tr>
  <tr class="field">
    <td class="tdleft"><%= f.label :title %></td>
    <td class="tdright"><%= f.text_field :title %></td>
  </tr>
  <tr class="field">
    <td class="tdleft"><%= f.label :startTime %></td>
    <td class="tdright"><%= f.date_select :startTime %></td>
  </tr>
  <tr class="field">
    <td class="tdleft"><%= f.label :endTime %></td>
    <td class="tdright"><%= f.date_select :endTime %></td>
  </tr>
  <tr class="field">
     <td class="tdleft"><%= f.label :category %></td>
     <td class="tdright"><%= f.select(:category ,{"beautify" => 1, "whitening" => 2, "hypertension" => 3, "diabetes" => 4}) %></td>
  </tr>

  <tr class="field">
     <td class="tdleft"><%= f.label :privilege %></td>
     <td class="tdright"><%= f.select( :privilege, { "all visible" => 1,  "friends visible" => 2, "private" => 3}) %></td>
  </tr>
  <tr class="field">
      <td class="tdleft"><%= f.label :text %></td>
      <td class="tdright"><%= f.text_area :text %></td>
  </tr>
   <%= f.hidden_field(:createTime) %>
   <%= f.hidden_field(:authorId) %>
  <tr class="actions">
    <td colspan="2"><%= f.submit %></td>
  </tr>
  </table>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'List', experiences_path %>

app/views/experiences/index.html.erb
<div class="contentdiv">
  <div style="border-bottom-style: inset; width: 85%; border-bottom-width: 1px">
  <table style="width: 100%">
    <tr>
      <td><h1>Listing experiences</h1></td>
      <td style="text-align: right"><%= link_to 'New Experience', new_experience_path %></td>
    </tr>
  </table>
  </div>
  <% @experiences.each do |experience| %>
  <div style="border-bottom-style: inset; width: 85%; border-bottom-width: 1px">
    <table style="width: 100%">
      <tr>
        <td><a href="/experiences?userid=<%= experience.authorId %>"><%= experience.getAuthorName %></a></td>
        <td style="text-align: right">published in &nbsp;&nbsp;<%= experience.createTime %></td>
      </tr>
      <tr>
        <td colspan="2" class="tdright" style="font-weight: bold; font-size: 24"><%= link_to experience.title, experience %></td>
      </tr>
      <tr>
        <td colspan="2" class="tdright"><%= experience.text %></td>
      </tr>
      <% if session[:userid] == experience.authorId %>
          <tr>
            <td class="tdleft" colspan="2">
              <%= link_to 'Edit', edit_experience_path(experience) %>
              <%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      <% if experience.getComments != nil %>
      <tr>
        <td colspan="2" class="tdright" style="font-weight: bold; font-size: 24;border-top-style: dashed; border-top-width: 1px">
          Comment List
        </td>
      </tr>
      <% experience.getComments.each do |comment| %>
        <tr>
          <td>
            <a href="/experiences?userid=<%= comment.authorId %>"><%= comment.getAuthorName %></a>
          </td>
          <td style="text-align: right">commented in &nbsp;&nbsp;<%= comment.createTime %></td>
        </tr>
        <tr>
          <td>
              <%= comment.content %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <% end %>
</div>
<br />

app/views/experiences/new.html.erb
<% if session[:user] == nil then %>
    <div class="warningdiv">
      <h1>To share your stories, your must <a href="/family_doctor/login">login</a></h1>
    </div>
<% else %>
<div class="contentdiv">
  <table class="contenttable">
      <tr style="background-color: #93A5C4">
        <td>
          <h1>Tell Your Story</h1>
        </td>
      </tr>
    <tr>
      <td>
        <%= render 'form' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to 'List', experiences_path %>
      </td>
    </tr>
  </table>
</div>
<% end %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<div class="contentdiv">
  <p style="background-color: #FFFFCC"><b class="titleFont">Body</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <% if session[:userid] == @experience.authorId %>
        <%= link_to 'Edit', edit_experience_path(@experience) %> |
        <%= link_to 'Destroy',experience_path(@experience), :method => :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
  <%= link_to 'To List', experiences_path %>
  </p>
  <div style="border-bottom-style: inset; width: 85%; border-bottom-style: none">
    <p>
        <b>Title:</b>
        <%= @experience.title %>
    </p>
    <% if session[:userid] != @experience.authorId  %>
        <p>
          <b>AuthorName:</b>
          <a href="/experiences?userid=<%= @experience.authorId %>"><%= @experience.getAuthorName %></a>
        </p>
    <% end %>
    <p>
      <b>Starttime:</b>
      <%= @experience.startTime %>
    </p>

    <p>
      <b>Endtime:</b>
      <%= @experience.endTime %>
    </p>

<p>
  <b>Createtime:</b>
  <%= @experience.createTime %>
</p>

<p>
  <b>Category:</b>
  <%= @experience.getCategoryName %>
</p>
    <p>
      <b>Content:</b>
      <%= @experience.text %>
    </p>
</div>

<p style="background-color: #FFFFCC"><b class="titleFont">Comments List</b></p>
<% @experience.getComments.each do |comment| %>
  <table style="width: 85%">
     <tr>
        <td>
          &nbsp;&nbsp;<a href="/experiences?userid=<%= comment.authorId %>"><%= comment.getAuthorName %></a>
        </td>
        <td style="text-align: right">commented in &nbsp;&nbsp;<%= comment.createTime %></td>
     </tr>
     <tr>
        <td>
          &nbsp;&nbsp;<%= comment.content %>
        </td>
     </tr>
  </table>
<% end %>

<p style="background-color: #FFFFCC"><b class="titleFont">Add Comment</b></p>
 <div style="width: 85%; vertical-align: middle">
 <table>
 <%= form_for(@comment) do |f| %>
    <%= f.hidden_field :experienceId %>
    <%= f.text_area :content %> <br>
    <%= f.submit 'add comment' %>
  <% end %>
 </table>
  </div>
</div>

app/views/family_doctor/login.html.erb
<p id="notice"><%= notice %></p>
<div style="height: 100%; width: 100%; vertical-align: middle">
    <table style="text-align: center; width: 75%; margin-left: auto; margin-right: auto; margin-top: 70px" border="2px">
      <tr style="height: 50px; background-color: #93A5C4">
        <td>
          <h1>Sign In </h1>
        </td>
      </tr>
      <tr>
        <td>
          <%= form_tag("/family_doctor/login", :method => :post) do %>
              <p>
                <%= label_tag "username" %>
                <%= text_field_tag "uName" %>  <br><a href="#">Forget username?</a><br>
              </p>

              <p>
                <%= label_tag "password" %>
                <%= password_field_tag "uPass" %><br> <a href="#">Forget password?</a><br>
              </p>
              <p>
                <%= submit_tag "login" %>&nbsp;&nbsp;&nbsp;&nbsp;
              </p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <a href="/family_doctor/register">Register</a> a user count.
        </td>
      </tr>
      <% if params[:source] == nil then %>
      <tr>
        <td>
          <div style="width: 100%; height: 40px">
            <div style="float: left">
              <a href="/family_doctor/login?source=renren"><%= image_tag "renren_logo.PNG" %></a> &nbsp;&nbsp;
              <a href="/family_doctor/login?source=qq"><%= image_tag "qq_logo.PNG" %></a>  &nbsp;&nbsp;
              <a href="/family_doctor/login?source=sina"><%= image_tag "sina_logo.PNG" %></a>  &nbsp;&nbsp;
              <a href="/family_doctor/login?source=alipay"><%= image_tag "alipag_logo.PNG" %></a>  &nbsp;&nbsp;
            </div>
          </div>
        </td>
      </tr>
      <% end %>
    </table>
</div>

app/views/family_doctor/register.html.erb
<h1>FamilyDoctor#register</h1>
<p>Find me in app/views/family_doctor/register.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Family Doctor</title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'rails' %>
  <%= yield(:head) %>
</head>
<body>

<div class="container">
  <div class="header">
    <% if session[:user] == nil then %>
        <div style="border-bottom-width: 1px; border-bottom-style: inset;width: 100%; height: 40px">
          <div style="float: right">
            <a href="/family_doctor/loginByOthers?source=renren"><%= image_tag "renren_logo.PNG" %></a> &nbsp;&nbsp;
            <a href="/family_doctor/loginByOthers?source=qq"><%= image_tag "qq_logo.PNG" %></a>  &nbsp;&nbsp;
            <a href="/family_doctor/loginByOthers?source=sina"><%= image_tag "sina_logo.PNG" %></a>  &nbsp;&nbsp;
            <a href="/family_doctor/loginByOthers?source=alipay"><%= image_tag "alipag_logo.PNG" %></a>  &nbsp;&nbsp;
          </div>
        </div>
    <% else %>
        <div style="border-bottom-width: 1px; border-bottom-style: inset;width: 100%; height: 40px">
          <div style="float: right">
            <a href="/experiences?userid=<%= session[:userid] %>"><%= session[:username] %></a>  &nbsp;&nbsp;&nbsp;
            <a href="/family_doctor/exit">exit</a>
          </div>
        </div>
    <% end %>
    <a href="#"><%= image_tag "header.jpg", :size => 1000*64 %></a>
  </div><!-- end .header -->
  <div class="sidebar1">
    <% if session[:user]==nil then %>
    <div>
      <%= form_tag("/family_doctor/login", :method => :post) do %>
          <p>
            <%= label_tag "username：" %><br>
            <%= text_field_tag "uName" %>
          </p>

          <p>
            <%= label_tag "password：" %><br>
            <%= password_field_tag "uPass" %>
          </p>
          <p>
            <%= submit_tag "login" %>&nbsp;&nbsp;&nbsp;&nbsp;  <a href="/family_doctor/register">Register</a>
          </p>
      <% end %>
    </div>
    <% end %>
    <ul class="nav">
      <li>
        <div><a href="#" >Food Composition</a></div>
        <ul class="nav">
          <li><a href="">meat</a></li>
          <li><a href="">legume</a></li>
          <li><a href="">seafood</a></li>
          <li><a href="">vegetables</a></li>
          <li><a href="">fruits</a></li>
        </ul>
      </li>
      <li>
        <div><a href="#">Dietary Therapy</a></div>
        <ul class="nav">
          <li><a href="">health maintenance</a></li>
          <li><a href="">beauty maintenance</a></li>
          <li><a href="">resist disease</a></li>
        </ul>
      </li>
      <li>
        <div><a href="/experiences">share experiences</a></div>
        <ul class="nav">
          <li><a href="/experiences?category=1">beautify</a></li>
          <li><a href="/experiences?category=2">whitening</a></li>
          <li><a href="/experiences?category=3">hypertension</a></li>
          <li><a href="/experiences?category=4">diabetes</a></li>
        </ul>
      </li>
      <li>
        <ul class="nav">
            <div><a href="#">Specialist Clinic</a></div>
        </ul>
      </li>
    </ul>
  </div>    <!-- end .sidebar1 -->
  <div class="content">
    <%= yield %>
  </div>
  <!-- end .content -->
  <div class="footer">
    <table>
      <tr>
        <td><a href="">About Us</a> |</td>
        <td><a href="">Contact Us |</a></td>
        <td> <%=Time.now%></td>
      </tr>
    </table>
  </div>    <!-- end .footer -->
</div>  <!-- end .container -->
</body>
</html>